#!/bin/bash
set -eo pipefail

host_groups="
Alpine:             audio=18,  dialout=20, uucp=14
CentOS/RedHat:      audio=63,  dialout=18, uucp=14
Debian/Ubuntu:      audio=29,  dialout=20, uucp=10
Linux from Scratch: audio=11,  dialout=10, uucp=32
openSUSE (old):     audio=17,  dialout=16, uucp=14
openSUSE (new):     audio=492, dialout=490
Raspberry Pi OS:    audio=29,  dialout=20, uucp=10, gpio=997
"

declare -A gid_name_array

# Map group IDs to group names
while read -r line; do
    IFS=',' read -r -a groups <<< "$(cut -d: -f2 <<< "$line" | tr -d ' ')"
    for group in "${groups[@]}"; do
        gid=$(cut -d= -f2 <<< "$group")
        if [[ ! -n "${gid_name_array[$gid]}" ]]; then
            name=$(cut -d= -f1 <<< "$group")
            gid_name_array[$gid]="$name"
        fi
    done
done <<< "$(sed '/^$/d' <<< "$host_groups")"

# Create missing groups and add user to groups
for gid in $(printf "%s\n" "${!gid_name_array[@]}" | sort -n); do
    name=${gid_name_array[$gid]}
    getent=$(getent group $gid || true)
    if [ "$getent" = "" ]; then
        i=""
        getent="$(getent group $name || true)"
        while [ -n "$getent" ]; do
            if [ "$i" = "" ]; then
                i=2
            else
                i=$((i + 1))
            fi
            getent="$(getent group $name$i || true)"
        done

        name="$name$i"
        groupadd -g $gid $name
    else
        name=$(cut -d: -f1 <<< $getent)
    fi

    adduser openhab $name
done
